"""add seq as real primary key for user_status_history ordering

Revision ID: 93ff0f3c1d98
Revises: 63ac9022c2da
Create Date: 2026-07-06 01:53:54.419045

`seq` replaces `id` as the primary key — a plain auto-incrementing
integer used purely for reliable ordering (see UserStatusHistory's
docstring: occurred_at + a UUID tiebreaker doesn't reliably preserve
insertion order). `id` stays as a separate unique UUID for external
reference. Hand-written, not the raw autogenerate output — the
autogenerated version didn't actually move the primary key from `id` to
`seq`, and didn't handle backfilling `seq` for this table's existing rows.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "93ff0f3c1d98"
down_revision: Union[str, None] = "63ac9022c2da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add seq as nullable first — existing rows don't have a value yet.
    op.add_column("user_status_history", sa.Column("seq", sa.Integer(), nullable=True))

    # Backfill existing rows in occurred_at order so `seq` reflects the
    # best available approximation of true insertion order for
    # already-existing history.
    op.execute(
        """
        UPDATE user_status_history
        SET seq = sub.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY occurred_at, id) AS rn
            FROM user_status_history
        ) AS sub
        WHERE user_status_history.id = sub.id
        """
    )

    # Move the primary key from id to seq; id becomes a separate unique column.
    op.drop_constraint("pk_user_status_history", "user_status_history", type_="primary")
    op.alter_column("user_status_history", "seq", nullable=False)
    op.create_primary_key("pk_user_status_history", "user_status_history", ["seq"])
    op.create_unique_constraint(
        op.f("uq_user_status_history_id"), "user_status_history", ["id"]
    )

    # Continue the sequence from after the backfilled rows for all future inserts.
    op.execute(
        "CREATE SEQUENCE IF NOT EXISTS user_status_history_seq_seq "
        "OWNED BY user_status_history.seq"
    )
    op.execute(
        "SELECT setval('user_status_history_seq_seq', "
        "COALESCE((SELECT MAX(seq) FROM user_status_history), 0) + 1, false)"
    )
    op.execute(
        "ALTER TABLE user_status_history ALTER COLUMN seq "
        "SET DEFAULT nextval('user_status_history_seq_seq')"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE user_status_history ALTER COLUMN seq DROP DEFAULT")
    op.execute("DROP SEQUENCE IF EXISTS user_status_history_seq_seq")
    op.drop_constraint(
        op.f("uq_user_status_history_id"), "user_status_history", type_="unique"
    )
    op.drop_constraint("pk_user_status_history", "user_status_history", type_="primary")
    op.create_primary_key("pk_user_status_history", "user_status_history", ["id"])
    op.drop_column("user_status_history", "seq")
