"""membership teams invitations audit trail settings history

Revision ID: e575ac4c036a
Revises:
Create Date: 2026-07-05 17:29:30.790932

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "e575ac4c036a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("performed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_events")),
    )
    op.create_index(
        "idx_organization_events_org_occurred",
        "organization_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_events_organization_id"),
        "organization_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_events_tenant_id"),
        "organization_events",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable organization name, e.g. 'Acme Corporation'.",
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-safe identifier, unique within the tenant.",
        ),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="active while operating; deleted is terminal (soft-delete).",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set on soft-delete; NULL means not deleted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','deleted')",
            name=op.f("ck_organizations_ck_organizations_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        "idx_organizations_tenant_slug",
        "organizations",
        ["tenant_id", "slug"],
        unique=True,
    )
    op.create_index(
        "idx_organizations_tenant_status",
        "organizations",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "organization_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','accepted','expired','revoked')",
            name=op.f(
                "ck_organization_invitations_ck_organization_invitations_valid_status"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_invitations")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("uq_organization_invitations_token_hash")
        ),
    )
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Projection reference to a User — not a FK, eventually consistent.",
        ),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_memberships")),
    )
    op.create_index(
        "idx_org_memberships_org_user",
        "organization_memberships",
        ["organization_id", "user_id"],
        unique=True,
    )
    op.create_table(
        "organization_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("default_member_role", sa.String(length=50), nullable=False),
        sa.Column("feature_flags", sa.JSON(), nullable=False),
        sa.Column("compliance_rules", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_settings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_settings")),
    )
    op.create_index(
        op.f("ix_organization_settings_organization_id"),
        "organization_settings",
        ["organization_id"],
        unique=True,
    )
    op.create_table(
        "organization_settings_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_settings_history_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_settings_history")),
    )
    op.create_index(
        "idx_org_settings_history_org_version",
        "organization_settings_history",
        ["organization_id", "version"],
        unique=True,
    )
    op.create_table(
        "organization_teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("team_type", sa.String(length=20), nullable=False),
        sa.Column("parent_team_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set on soft-delete; NULL means not deleted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','deleted')",
            name=op.f("ck_organization_teams_ck_organization_teams_valid_status"),
        ),
        sa.CheckConstraint(
            "team_type IN ('team','department')",
            name=op.f("ck_organization_teams_ck_organization_teams_valid_type"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_teams_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_team_id"],
            ["organization_teams.id"],
            name=op.f("fk_organization_teams_parent_team_id_organization_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_teams")),
    )
    op.create_index(
        "idx_organization_teams_org_name",
        "organization_teams",
        ["organization_id", "name"],
        unique=True,
    )
    op.create_table(
        "team_memberships",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["organization_teams.id"],
            name=op.f("fk_team_memberships_team_id_organization_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id", name=op.f("pk_team_memberships")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_memberships")
    op.drop_index("idx_organization_teams_org_name", table_name="organization_teams")
    op.drop_table("organization_teams")
    op.drop_index(
        "idx_org_settings_history_org_version",
        table_name="organization_settings_history",
    )
    op.drop_table("organization_settings_history")
    op.drop_index(
        op.f("ix_organization_settings_organization_id"),
        table_name="organization_settings",
    )
    op.drop_table("organization_settings")
    op.drop_index("idx_org_memberships_org_user", table_name="organization_memberships")
    op.drop_table("organization_memberships")
    op.drop_table("organization_invitations")
    op.drop_index("idx_organizations_tenant_status", table_name="organizations")
    op.drop_index("idx_organizations_tenant_slug", table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(
        op.f("ix_organization_events_tenant_id"), table_name="organization_events"
    )
    op.drop_index(
        op.f("ix_organization_events_organization_id"), table_name="organization_events"
    )
    op.drop_index(
        "idx_organization_events_org_occurred", table_name="organization_events"
    )
    op.drop_table("organization_events")
    # ### end Alembic commands ###
