"""initial user lifecycle schema

Revision ID: 0ab060732dc7
Revises:
Create Date: 2026-07-05 20:35:42.740019

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0ab060732dc7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lifecycle_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("from_status", sa.String(length=50), nullable=True),
        sa.Column("to_status", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("performed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lifecycle_events")),
    )
    op.create_index(
        "idx_lifecycle_events_user_occurred",
        "lifecycle_events",
        ["user_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "lifecycle_states",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning user (projection — not a FK; UserManagement owns the real row).",
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("locked_reason", sa.String(length=500), nullable=True),
        sa.Column("locked_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','suspended','locked','deactivated')",
            name=op.f("ck_lifecycle_states_ck_lifecycle_states_valid_status"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_lifecycle_states")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lifecycle_states")
    op.drop_index("idx_lifecycle_events_user_occurred", table_name="lifecycle_events")
    op.drop_table("lifecycle_events")
    # ### end Alembic commands ###
