"""initial schema

Revision ID: e4d3f0a5eb84
Revises: 
Create Date: 2026-07-11 14:15:19.063622

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4d3f0a5eb84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_decision_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caller_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('target_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_decision_logs'))
    )
    op.create_index('idx_access_decision_logs_caller_tenant', 'access_decision_logs', ['caller_tenant_id'], unique=False)
    op.create_index('idx_access_decision_logs_decided_at', 'access_decision_logs', ['decided_at'], unique=False)
    op.create_index('idx_access_decision_logs_decision', 'access_decision_logs', ['decision'], unique=False)
    op.create_table('isolation_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('allow_cross_tenant_read', sa.Boolean(), nullable=False),
    sa.Column('allowed_partner_tenant_ids', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isolation_policies'))
    )
    op.create_index('idx_isolation_policies_tenant_active', 'isolation_policies', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_isolation_policies_tenant_id', 'isolation_policies', ['tenant_id'], unique=False)
    op.create_table('resource_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('source_service', sa.String(length=200), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_claims')),
    sa.UniqueConstraint('resource_type', 'resource_id', name='uq_resource_claims_type_id')
    )
    op.create_index('idx_resource_claims_tenant_id', 'resource_claims', ['tenant_id'], unique=False)
    op.create_index('idx_resource_claims_type_id', 'resource_claims', ['resource_type', 'resource_id'], unique=False)
    op.create_table('tenant_connections',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('db_driver', sa.String(length=64), nullable=False),
    sa.Column('db_host', sa.String(length=255), nullable=False),
    sa.Column('db_port', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=255), nullable=False),
    sa.Column('db_user', sa.String(length=255), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_tenant_connections'))
    )
    op.create_index('idx_tenant_connections_subdomain', 'tenant_connections', ['subdomain'], unique=True)
    op.create_table('tenant_lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('transition', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_lifecycle_events'))
    )
    op.create_index('idx_lifecycle_events_tenant_occurred', 'tenant_lifecycle_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_tenant_lifecycle_events_tenant_id'), 'tenant_lifecycle_events', ['tenant_id'], unique=False)
    op.create_table('tenant_lifecycle_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='External tenant identifier. Not a FK — projection pattern.'),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_lifecycle_states')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_lifecycle_states_tenant_id'))
    )
    op.create_index('idx_lifecycle_states_tenant_id', 'tenant_lifecycle_states', ['tenant_id'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Globally unique URL-safe slug.'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='Human-readable tenant name.'),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current lifecycle state.'),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False, comment='Primary owner user_id (projection — not a FK to User Service).'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Set on soft-delete; NULL means not deleted.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft','provisioning','pending','active','suspended','archived','deleted')", name=op.f('ck_tenants_ck_tenants_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('name', name=op.f('uq_tenants_name'))
    )
    op.create_index('idx_tenants_name', 'tenants', ['name'], unique=True)
    op.create_index('idx_tenants_status_region', 'tenants', ['status', 'region'], unique=False)
    op.create_table('tenant_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Owner user_id — projection, not a FK to User Service.'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='owner | admin'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when contact is removed. NULL means currently active.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_contacts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_contacts'))
    )
    op.create_index('idx_tenant_contacts_active', 'tenant_contacts', ['tenant_id', 'removed_at'], unique=False)
    op.create_index('idx_tenant_contacts_tenant_user', 'tenant_contacts', ['tenant_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_tenant_contacts_tenant_id'), 'tenant_contacts', ['tenant_id'], unique=False)
    op.create_table('tenant_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_metadata_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_metadata'))
    )
    op.create_index('idx_tenant_metadata_tenant_key', 'tenant_metadata', ['tenant_id', 'key'], unique=True)
    op.create_index(op.f('ix_tenant_metadata_tenant_id'), 'tenant_metadata', ['tenant_id'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('number_format', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('default_theme', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_settings'))
    )
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_tenant_metadata_tenant_id'), table_name='tenant_metadata')
    op.drop_index('idx_tenant_metadata_tenant_key', table_name='tenant_metadata')
    op.drop_table('tenant_metadata')
    op.drop_index(op.f('ix_tenant_contacts_tenant_id'), table_name='tenant_contacts')
    op.drop_index('idx_tenant_contacts_tenant_user', table_name='tenant_contacts')
    op.drop_index('idx_tenant_contacts_active', table_name='tenant_contacts')
    op.drop_table('tenant_contacts')
    op.drop_index('idx_tenants_status_region', table_name='tenants')
    op.drop_index('idx_tenants_name', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('idx_lifecycle_states_tenant_id', table_name='tenant_lifecycle_states')
    op.drop_table('tenant_lifecycle_states')
    op.drop_index(op.f('ix_tenant_lifecycle_events_tenant_id'), table_name='tenant_lifecycle_events')
    op.drop_index('idx_lifecycle_events_tenant_occurred', table_name='tenant_lifecycle_events')
    op.drop_table('tenant_lifecycle_events')
    op.drop_index('idx_tenant_connections_subdomain', table_name='tenant_connections')
    op.drop_table('tenant_connections')
    op.drop_index('idx_resource_claims_type_id', table_name='resource_claims')
    op.drop_index('idx_resource_claims_tenant_id', table_name='resource_claims')
    op.drop_table('resource_claims')
    op.drop_index('idx_isolation_policies_tenant_id', table_name='isolation_policies')
    op.drop_index('idx_isolation_policies_tenant_active', table_name='isolation_policies')
    op.drop_table('isolation_policies')
    op.drop_index('idx_access_decision_logs_decision', table_name='access_decision_logs')
    op.drop_index('idx_access_decision_logs_decided_at', table_name='access_decision_logs')
    op.drop_index('idx_access_decision_logs_caller_tenant', table_name='access_decision_logs')
    op.drop_table('access_decision_logs')
    # ### end Alembic commands ###
