"""initial schema

Revision ID: 35cabc56b647
Revises: 
Create Date: 2026-06-27 15:20:31.194637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cabc56b647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Globally unique URL-safe slug.'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='Human-readable tenant name.'),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current lifecycle state.'),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False, comment='Primary owner user_id (projection — not a FK to User Service).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Set on soft-delete; NULL means not deleted.'),
    sa.CheckConstraint("status IN ('draft','provisioning','active','suspended','archived','deleted')", name=op.f('ck_tenants_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('name', name=op.f('uq_tenants_name'))
    )
    op.create_index('idx_tenants_name', 'tenants', ['name'], unique=True)
    op.create_index('idx_tenants_status_region', 'tenants', ['status', 'region'], unique=False)
    op.create_table('tenant_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Owner user_id — projection, not a FK to User Service.'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='owner | admin'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when contact is removed. NULL means currently active.'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_contacts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_contacts'))
    )
    op.create_index('idx_tenant_contacts_active', 'tenant_contacts', ['tenant_id', 'removed_at'], unique=False)
    op.create_index('idx_tenant_contacts_tenant_user', 'tenant_contacts', ['tenant_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_tenant_contacts_tenant_id'), 'tenant_contacts', ['tenant_id'], unique=False)
    op.create_table('tenant_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_metadata_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_metadata'))
    )
    op.create_index('idx_tenant_metadata_tenant_key', 'tenant_metadata', ['tenant_id', 'key'], unique=True)
    op.create_index(op.f('ix_tenant_metadata_tenant_id'), 'tenant_metadata', ['tenant_id'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('number_format', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('default_theme', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_settings'))
    )
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_tenant_metadata_tenant_id'), table_name='tenant_metadata')
    op.drop_index('idx_tenant_metadata_tenant_key', table_name='tenant_metadata')
    op.drop_table('tenant_metadata')
    op.drop_index(op.f('ix_tenant_contacts_tenant_id'), table_name='tenant_contacts')
    op.drop_index('idx_tenant_contacts_tenant_user', table_name='tenant_contacts')
    op.drop_index('idx_tenant_contacts_active', table_name='tenant_contacts')
    op.drop_table('tenant_contacts')
    op.drop_index('idx_tenants_status_region', table_name='tenants')
    op.drop_index('idx_tenants_name', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
