"""initial user profile schema

Revision ID: e87bad948a03
Revises:
Create Date: 2026-07-06 00:19:18.709363

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e87bad948a03"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "avatars",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning user (projection — not a FK; UserManagement owns the real row).",
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_avatars")),
    )
    op.create_table(
        "contact_info",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning user (projection — not a FK; UserManagement owns the real row).",
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("secondary_email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_contact_info")),
    )
    op.create_table(
        "user_preferences",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning user (projection — not a FK; UserManagement owns the real row).",
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "user_profiles",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning user (projection — not a FK; UserManagement owns the real row).",
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("bio", sa.String(length=2000), nullable=True),
        sa.Column("pronouns", sa.String(length=50), nullable=True),
        sa.Column("display_name_override", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    op.drop_table("user_preferences")
    op.drop_table("contact_info")
    op.drop_table("avatars")
    # ### end Alembic commands ###
