"""Application-wide constants."""

TENANT_NAME_MAX_LENGTH: int = 255
TENANT_SLUG_PATTERN: str = r"^[a-z0-9][a-z0-9-]*[a-z0-9]$"
TENANT_DESCRIPTION_MAX_LENGTH: int = 1000

DEFAULT_PAGINATION_LIMIT: int = 20
MAX_PAGINATION_LIMIT: int = 100

DEFAULT_TIMEZONE: str = "UTC"
DEFAULT_LOCALE: str = "en-US"
DEFAULT_CURRENCY: str = "USD"
DEFAULT_LANGUAGE: str = "en"
DEFAULT_DATE_FORMAT: str = "YYYY-MM-DD"
DEFAULT_SESSION_TIMEOUT_MINUTES: int = 60
DEFAULT_THEME: str = "light"
