"""Backward-compatibility shim — canonical definition moved to tenants_router.py."""

from app.api.v1.tenants_router import (
    activate_tenant,
    add_owner,
    archive_tenant,
    create_tenant,
    delete_tenant,
    get_metadata,
    get_settings,
    get_tenant,
    list_owners,
    list_tenants,
    provision_tenant,
    remove_owner,
    router,
    suspend_tenant,
    update_metadata,
    update_settings,
    update_tenant,
)

__all__ = [
    "activate_tenant",
    "add_owner",
    "archive_tenant",
    "create_tenant",
    "delete_tenant",
    "get_metadata",
    "get_settings",
    "get_tenant",
    "list_owners",
    "list_tenants",
    "provision_tenant",
    "remove_owner",
    "router",
    "suspend_tenant",
    "update_metadata",
    "update_settings",
    "update_tenant",
]
