"""add audit_events table

Revision ID: d2d396cf5a68
Revises: f7a56e37b6a5
Create Date: 2026-07-06 00:49:12.652905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2d396cf5a68"
down_revision: Union[str, Sequence[str], None] = "f7a56e37b6a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column(
            "subject_user_id",
            sa.Uuid(),
            nullable=True,
            comment="The user whose access changed, if applicable.",
        ),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor_id",
            sa.Uuid(),
            nullable=True,
            comment="Caller-supplied, unverified — see module docstring.",
        ),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "idx_audit_events_subject_occurred",
        "audit_events",
        ["subject_user_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "idx_audit_events_tenant_occurred",
        "audit_events",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_audit_events_tenant_occurred", table_name="audit_events")
    op.drop_index("idx_audit_events_subject_occurred", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
