"""initial iam schema

Revision ID: f7a56e37b6a5
Revises:
Create Date: 2026-07-05 13:20:53.815292

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7a56e37b6a5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column(
            "subject_user_id",
            sa.Uuid(),
            nullable=False,
            comment="The user whose access is under review.",
        ),
        sa.Column(
            "reviewer_id",
            sa.Uuid(),
            nullable=True,
            comment="The user performing the review; NULL until assigned.",
        ),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("decision_notes", sa.String(length=2000), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','approved','revoked')",
            name=op.f("ck_access_reviews_ck_access_reviews_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_reviews")),
    )
    op.create_table(
        "attributes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Projection reference to user_projections.id — not a FK (eventually-consistent, see GroupMembership).",
        ),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attributes")),
    )
    op.create_index(
        "idx_attributes_tenant_user_key",
        "attributes",
        ["tenant_id", "user_id", "key"],
        unique=True,
    )
    op.create_table(
        "entitlements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Projection reference to user_projections.id — not a FK (eventually-consistent, see GroupMembership).",
        ),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set on soft-delete; NULL means not deleted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','revoked')",
            name=op.f("ck_entitlements_ck_entitlements_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlements")),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="active while usable; deleted is terminal (soft-delete).",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set on soft-delete; NULL means not deleted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','deleted')",
            name=op.f("ck_groups_ck_groups_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
    )
    op.create_index(
        "idx_groups_tenant_name", "groups", ["tenant_id", "name"], unique=True
    )
    op.create_index(
        "idx_groups_tenant_status", "groups", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Convention: 'resource:action', e.g. 'users:read'.",
        ),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="active while usable; deleted is terminal (soft-delete).",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set on soft-delete; NULL means not deleted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','deleted')",
            name=op.f("ck_permissions_ck_permissions_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
    )
    op.create_index(
        "idx_permissions_tenant_name", "permissions", ["tenant_id", "name"], unique=True
    )
    op.create_index(
        "idx_permissions_tenant_status",
        "permissions",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Owning tenant (projection — not a FK to Tenent's database).",
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="active while usable; deleted is terminal (soft-delete).",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set on soft-delete; NULL means not deleted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','deleted')",
            name=op.f("ck_roles_ck_roles_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(
        "idx_roles_tenant_name", "roles", ["tenant_id", "name"], unique=True
    )
    op.create_index(
        "idx_roles_tenant_status", "roles", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "user_id", name=op.f("pk_tenant_memberships")
        ),
    )
    op.create_table(
        "user_projections",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="User identifier originating from User Service.",
        ),
        sa.Column(
            "tenant_id", sa.Uuid(), nullable=False, comment="Owning tenant identifier."
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Replicated email address from User Service.",
        ),
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=False,
            comment="User display name replicated from User Service.",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Current user lifecycle status.",
        ),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last successful synchronization timestamp.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_projections")),
    )
    op.create_index(
        "idx_user_projection_tenant_email",
        "user_projections",
        ["tenant_id", "email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_projections_email"), "user_projections", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_user_projections_tenant_id"),
        "user_projections",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "group_memberships",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_group_memberships_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id", "user_id", name=op.f("pk_group_memberships")
        ),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_id", name=op.f("pk_role_permissions")
        ),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Defense-in-depth scoping column; role_id already implies a tenant via roles.tenant_id.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_user_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("group_memberships")
    op.drop_index(op.f("ix_user_projections_tenant_id"), table_name="user_projections")
    op.drop_index(op.f("ix_user_projections_email"), table_name="user_projections")
    op.drop_index("idx_user_projection_tenant_email", table_name="user_projections")
    op.drop_table("user_projections")
    op.drop_table("tenant_memberships")
    op.drop_index("idx_roles_tenant_status", table_name="roles")
    op.drop_index("idx_roles_tenant_name", table_name="roles")
    op.drop_table("roles")
    op.drop_index("idx_permissions_tenant_status", table_name="permissions")
    op.drop_index("idx_permissions_tenant_name", table_name="permissions")
    op.drop_table("permissions")
    op.drop_index("idx_groups_tenant_status", table_name="groups")
    op.drop_index("idx_groups_tenant_name", table_name="groups")
    op.drop_table("groups")
    op.drop_table("entitlements")
    op.drop_index("idx_attributes_tenant_user_key", table_name="attributes")
    op.drop_table("attributes")
    op.drop_table("access_reviews")
    # ### end Alembic commands ###
