"""Application-wide constants."""

DEFAULT_PAGINATION_LIMIT: int = 20
MAX_PAGINATION_LIMIT: int = 100
MAX_RESOURCE_IDS_PER_REQUEST: int = 100
MAX_RESOURCE_ID_LENGTH: int = 500

CACHE_TTL_POLICY: int = 120
CACHE_TTL_CLAIM: int = 300
CACHE_TTL_ALLOW_DECISION: int = 60
CACHE_TTL_DENY_DECISION: int = 30
